print("*******PRACTICE DAY-1**********")
print("initialization of variable")
a=20
print("inbuilt functions")
print(a)
print(type(a))
print(id(a))
print("mathematical inbuilt functions")
b=10.342
print(int(b))
print(complex(b))
print(float(b))
print(bool(b))
print("number system conversions")
c=15
print(bin(c))
print(hex(c))
print(oct(c))
print("slice operator")
print('string[start:end:step]')
str="my python class"
print(str[0:5])    
print(str[2:12:2]) 
print(str[-1:-6:-1]) 
print(str[-2:8:-1])
print(str[::-1])
